version: '3.7'
services:
  refbox:
    image: "registry.gitlab.com/grips_robocup/team_server/refbox:refactored"
    entrypoint: bash -c "sleep 25 && ./start.sh"
    network_mode: "host"
    depends_on:
      - mongodb
    restart: "always"
    volumes:
      - ./../config/refbox/game.yaml:/etc/rcll-refbox/game/default_game.yaml
      - ./../config/refbox/simulation.yaml:/etc/rcll-refbox/simulation/default_simulation.yaml
      - ./../config/refbox/comm.yaml:/etc/rcll-refbox/comm/default_comm.yaml
      - ./../config/refbox/mps.yaml:/etc/rcll-refbox/mps/default_mps.yaml
      - ./../config/refbox/team.yaml:/etc/rcll-refbox/team/default_team.yaml

  frontend:
    image: "registry.gitlab.com/grips_robocup/logistics/rcll-frontend"
    network_mode: "host"
    restart: "always"
    ports:
      - 80:80
  mongodb:
    network_mode: "host"
    image: mongo
    restart: "always"
    container_name: "mongodb"
